services:
  - docker
script:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker build --build-arg NODE_VERSION=$NODE -t softinstigate/angular-docker . ;
      docker tag softinstigate/angular-docker:latest "softinstigate/angular-docker:$NODE";
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin;
      docker push softinstigate/angular-docker:$NODE;
      docker push softinstigate/angular-docker:latest;
    fi
env:
  global:
    - NODE=10.21
